// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TerrorIncidentAPI;

#nullable disable

namespace TerrorIncidentAPI.Migrations
{
    [DbContext(typeof(TerrorIncidentDbContext))]
    partial class TerrorIncidentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TerrorIncidentAPI.Models.Incident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Confidence")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuicide")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("Latitude")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Longitude")
                        .HasColumnType("int");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Target")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.Property<int?>("Weapon")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("TerrorIncidentAPI.Models.Incident", b =>
                {
                    b.OwnsOne("TerrorIncidentAPI.Models.Attacker", "Attacker", b1 =>
                        {
                            b1.Property<int>("IncidentId")
                                .HasColumnType("int");

                            b1.Property<bool>("ClaimedResponsibility")
                                .HasColumnType("bit");

                            b1.Property<string>("Motive")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("NumberOfPerpetrators")
                                .HasColumnType("int");

                            b1.Property<string>("PerpetratorGroup")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("IncidentId");

                            b1.ToTable("Incidents");

                            b1.WithOwner()
                                .HasForeignKey("IncidentId");
                        });

                    b.OwnsOne("TerrorIncidentAPI.Models.Casualties", "Casualties", b1 =>
                        {
                            b1.Property<int>("IncidentId")
                                .HasColumnType("int");

                            b1.Property<int?>("Fatalities")
                                .HasColumnType("int");

                            b1.Property<int?>("Injuries")
                                .HasColumnType("int");

                            b1.HasKey("IncidentId");

                            b1.ToTable("Incidents");

                            b1.WithOwner()
                                .HasForeignKey("IncidentId");
                        });

                    b.Navigation("Attacker");

                    b.Navigation("Casualties");
                });
#pragma warning restore 612, 618
        }
    }
}
